{% set version = "6.0.2" %}

package:
  name: md-toc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/md_toc/md_toc-{{ version }}.tar.gz
  sha256: d8145bf367d5734a8acb4de8c64251bd02a5d7aa1a3171f38fe55d140cb482a4

build:
  number: 0
  noarch: python
  entry_points:
    - md_toc = md_toc.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
    - fpyutils >=0.0.2
  run:
    - python >=3
    - setuptools
    - fpyutils >=0.0.2

test:
  imports:
    - md_toc
  commands:
    - md_toc --help

about:
  home: https://github.com/frnmst/md-toc
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'An utility that is able to generate a table of contents for a markdown file'

extra:
  recipe-maintainers:
    - ocefpaf
