{% set version = "6.0.0" %}

package:
  name: md-toc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/md_toc/md_toc-{{ version }}.tar.gz
  sha256: 7e0e84f648545968b18ab904c85f4cb744d6995ee315ae6820630a1f1cc06f8d

build:
  number: 0
  noarch: python
  entry_points:
    - md_toc = md_toc.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
    - fpyutils >=0.0.2
  run:
    - python >=3
    - setuptools
    - fpyutils >=0.0.2

test:
  imports:
    - md_toc
  commands:
    - md_toc --help

about:
  home: https://github.com/frnmst/md-toc
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: 'An utility that is able to generate a table of contents for a markdown file'

extra:
  recipe-maintainers:
    - ocefpaf
