travis:
  secure:
    BINSTAR_TOKEN: R9JDk86sAwGS6RiZkwVautuHIjCWTJwlN8RvM5YPvlMgP1VtB8o954XdLLgRaL4cq3+qr187XnMaRgKFytCc6sSY9h7NfhbDfpTx96wRjfRexjgX//ZM0uumKsfGWMkIk3dEZ4DvX3ay8BKcWpOcpR3qGqXPsmrI+OWFHGt63GJAEphZfX9utdm3QCoEaELQ7mAt4bndLa0z7sRVeYuMdN3Yz2dz9cok2mLUqtp7cBFrTFCl8Vv/A+WevjvybIcET3HmJRsLykcmx2w0Z+KxP31KsxPzgB5hPunBo6d3DZ0CQSyROvb3AcLWa+p/Rrk3iYWzyK/oIaAH6fMBQtqKb/Iz5nE5iC8VHmN7oM5WBgKYw2s/grcwY28deDSUEbIPD0DGZ1Pp+RAjvU7zjgByZnTX50javzab76Bdi4aFrvJfqR+jHR+dMKFDt9J+0zrsn2jvYei8qJnPQw+tUpWPSfk8Z2ZTSHbg5AR7Y4oFq0Yz/HYVm76Yrlro4uw4CWleQhPIyxmcA/ngPY0H9P1mTajs4MWvC/4ee8b/gAKudx/BAsDNPrY2tpuUKe8l/zCGr6BcQAdpbq0/gOAKXG9N4D2Mcui79ll7/RG1EgPUHvo57Bzx/4AuYWzDQv0FWRumH+QwK+CDQsFpyUF8eW6P4MK6tjsB1Pbme8peLVJJFSg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
